# Generated by Django 4.2.5 on 2024-01-26 11:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('total_bonus', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ish_vaqti', models.CharField(max_length=30)),
                ('ism', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Drivers.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.PositiveBigIntegerField(default=0)),
                ('baggage', models.BooleanField(default=False)),
                ('for_women', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('olindi', 'olindi'), ('boshlandi', 'boshlandi'), ('tugadi', 'tugadi'), ('bekor qilindi', 'bekor qilindi')], max_length=30)),
                ('starting_point', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('grading_point', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('waiting_seconds', models.PositiveSmallIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.client')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drivers.driver')),
            ],
        ),
    ]
